// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igewokzoydrqxjncuefp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZXdva3pveWRycXhqbmN1ZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzQ1MTksImV4cCI6MjA2ODA1MDUxOX0.0OOR2ioXcp8eK3wHAzWznfgvp54VRSPk6DQKHkON6w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});